#!/bin/sh
set -e

echo "▶ ci_post_clone: starting"

# 1. Guard — fail loudly if the secret wasn't set in the workflow
if [ -z "$TMDB_KEY" ]; then
	echo "❌ ERROR: TMDB_KEY environment variable is not set."
	echo " Add it as a secret in your Xcode Cloud workflow settings."
	exit 1
fi

# 2. CI_PRIMARY_REPOSITORY_PATH is always injected by Xcode Cloud
PROJECT_ROOT="$CI_PRIMARY_REPOSITORY_PATH"
CONFIG_DIR="$PROJECT_ROOT"

echo "▶ Project root: $PROJECT_ROOT"

# 3. Write Secrets.xcconfig from the env var
mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_DIR/Secrets.xcconfig" << EOF
// Auto-generated by ci_post_clone.sh — DO NOT COMMIT
TMDB_KEY = $TMDB_KEY
EOF

echo "✅  Secrets.xcconfig written to $CONFIG_DIR"
echo "▶ ci_post_clone: done"